services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: laravel-excercise
        container_name: laravel-excercise
        volumes:
            - .:/var/www
        ports:
            - "8084:8000"
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: laravel-excercise-mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel-excercise-nginx
        ports:
            - "8082:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
        driver: bridge
